name: api_rest_connect
description: A robust HTTP REST client plugin with advanced error handling and logging capabilities.
version: 1.0.0
homepage: https://github.com/identaplusschool/api_rest_connect_plugin

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
